<?php

namespace App\Http\Controllers\Home;

use App\Traits\Priority;

class SonController extends Base
{
    use Priority;
    public function index()
    {
        echo '这是当前类sonController的方法 index()';
    }

    /*public function edit()
    {
        //parent::edit(); // TODO: Change the autogenerated stub
    }*/
}
