<?php
/**
 * Created by PhpStorm.
 * User: liyi
 * Date: 2019/2/15
 * Time: 17:48
 */
namespace App\Http\Controllers\Observer;

class LocationOne extends Liyi
{
    public function disPlay()
    {
        echo "穿好衣服，\n";
        parent::disPlay(); // TODO: Change the autogenerated stub
    }
}
