<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use Illuminate\Http\Request;

use App\Notifications\InvoicePaid;

class NewsController extends BaseController
{
    public function test()
    {
        echo new BaseController();
    }

    public function __call($method, $parameters)
    {
        parent::__call($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function createUser(Request $request)
    {
        $request = [
            'username' => 'admin',
            'account'  => 'adminRoot',
            'password' => '',
            'token'    => '',
            'email'    => '',
            'mobile'   => '',
            'QQ'       => '',
            'github'   => ''
        ];
    }

    public function index()
    {
        /**
         * 调用 User 中的 notify 方法，并新建一个通知实例作为参数传入
           也可以通过重写 User 类的 notify 方法来实现更多的操作，但最后需要调用 Notifiable.notify 方法来发送通知
         */
        $user = new User();
        $user->notify(new InvoicePaid($invoice));
    }

}
